const SOURCE_CATALOG = [
  {
    id: "secop-ii",
    name: "SECOP II",
    tier: "nacional",
    connector: "secopOpenData",
    domains: ["colombiacompra.gov.co", "secop.gov.co"],
    seedUrls: ["https://www.colombiacompra.gov.co/secop/secop-ii"],
  },
  {
    id: "apc-colombia",
    name: "APC Colombia",
    tier: "nacional",
    domains: ["apccolombia.gov.co"],
    seedUrls: ["https://www.apccolombia.gov.co/convocatorias"],
  },
  {
    id: "minciencias",
    name: "Minciencias",
    tier: "nacional",
    connector: "mincienciasActeiPlan",
    domains: ["minciencias.gov.co"],
    seedUrls: ["https://minciencias.gov.co/plan-convocatorias-actei-2025-2026-0"],
  },
  {
    id: "mintic",
    name: "MinTIC",
    tier: "nacional",
    domains: ["mintic.gov.co"],
    seedUrls: ["https://www.mintic.gov.co/portal/inicio/convocatorias/"],
  },
  {
    id: "minambiente",
    name: "MinAmbiente",
    tier: "nacional",
    domains: ["minambiente.gov.co"],
    seedUrls: ["https://www.minambiente.gov.co/"],
  },
  {
    id: "dps",
    name: "DPS",
    tier: "nacional",
    domains: ["prosperidadsocial.gov.co"],
    seedUrls: ["https://prosperidadsocial.gov.co/"],
  },
  {
    id: "sgr",
    name: "SGR",
    tier: "nacional",
    domains: ["sgr.gov.co", "dnp.gov.co"],
    seedUrls: ["https://www.sgr.gov.co/"],
  },
  {
    id: "gobernaciones",
    name: "Gobernaciones",
    tier: "nacional",
    domains: ["gov.co"],
    seedUrls: ["https://www.gov.co/"],
  },
  {
    id: "findeter",
    name: "Findeter",
    tier: "nacional",
    domains: ["findeter.gov.co"],
    seedUrls: ["https://www.findeter.gov.co/"],
  },
  {
    id: "pnud",
    name: "PNUD",
    tier: "internacional",
    domains: ["undp.org"],
    seedUrls: ["https://www.undp.org/procurement/business-opportunities"],
  },
  {
    id: "ted-europa",
    name: "TED Europa",
    tier: "internacional",
    connector: "tedEuSearch",
    connectorQueries: [
      "publication-date>=today(-30) AND notice-type=cn-standard",
      "publication-date>=today(-30) AND notice-type=cn-standard AND notice-title~\"social\"",
      "publication-date>=today(-30) AND notice-type=cn-standard AND notice-title~\"education\"",
      "publication-date>=today(-30) AND notice-type=cn-standard AND notice-title~\"environment\"",
    ],
    domains: ["ted.europa.eu", "europa.eu"],
    seedUrls: ["https://ted.europa.eu/"],
  },
  {
    id: "europeaid",
    name: "Union Europea (EuropeAid)",
    tier: "internacional",
    domains: ["europa.eu", "ec.europa.eu"],
    seedUrls: ["https://international-partnerships.ec.europa.eu/funding_en"],
  },
  {
    id: "bid-lab",
    name: "BID Lab",
    tier: "internacional",
    domains: ["bidlab.org", "iadb.org"],
    seedUrls: ["https://bidlab.org/en/calls"],
  },
  {
    id: "caf",
    name: "CAF",
    tier: "internacional",
    domains: ["caf.com"],
    seedUrls: ["https://www.caf.com/en/"],
  },
  {
    id: "world-bank",
    name: "Banco Mundial",
    tier: "internacional",
    domains: ["worldbank.org"],
    seedUrls: ["https://www.worldbank.org/en/projects-operations/procurement"],
  },
  {
    id: "gef-small-grants",
    name: "GEF Small Grants",
    tier: "internacional",
    domains: ["sgp.undp.org", "thegef.org"],
    seedUrls: ["https://sgp.undp.org/"],
  },
  {
    id: "usaid",
    name: "USAID",
    tier: "internacional",
    connector: "grantsGovSearch2",
    connectorKeywords: [
      "community development",
      "education",
      "climate",
      "social inclusion",
      "institutional strengthening",
      "rural development",
      "innovation",
      "territorial",
    ],
    domains: ["usaid.gov", "grants.gov"],
    seedUrls: ["https://www.usaid.gov/work-usaid/partner-with-us"],
  },
  {
    id: "giz",
    name: "GIZ",
    tier: "internacional",
    domains: ["giz.de"],
    seedUrls: ["https://www.giz.de/en/worldwide/109163.html"],
  },
  {
    id: "embajadas",
    name: "Embajadas",
    tier: "internacional",
    domains: ["embassy", "gov"],
    seedUrls: ["https://www.cancilleria.gov.co/"],
  },
  {
    id: "google-org",
    name: "Google.org",
    tier: "internacional",
    domains: ["google.org"],
    seedUrls: ["https://www.google.org/open-calls/"],
  },
  {
    id: "climate-funds",
    name: "Climate Funds",
    tier: "internacional",
    domains: ["climateinvestmentfunds.org", "greenclimate.fund"],
    seedUrls: ["https://www.climateinvestmentfunds.org/"],
  },
];

const DISCOVERY_KEYWORDS = [
  "convocatoria",
  "subvencion",
  "cooperacion",
  "grant",
  "funding",
  "proposal",
  "call for proposals",
  "project",
  "territorial",
  "social",
  "ngo",
  "non-profit",
  "fundacion",
];

const OPPORTUNITY_URL_HINTS = [
  "convoc",
  "grant",
  "call",
  "proposal",
  "funding",
  "licit",
  "opportun",
  "subvencion",
  "cooper",
  "procurement",
];

module.exports = {
  SOURCE_CATALOG,
  DISCOVERY_KEYWORDS,
  OPPORTUNITY_URL_HINTS,
};
