const SOURCE_CATALOG = [
  {
    id: "secop-ii",
    name: "SECOP II",
    tier: "nacional",
    connector: "secopOpenData",
    domains: ["colombiacompra.gov.co", "secop.gov.co"],
    searchKeywords: [
      "SECOP II convocatoria abierta",
      "SECOP II licitacion publica",
      "SECOP II seleccion abreviada",
      "SECOP II minima cuantia",
      "SECOP II proyectos inversion publica",
      "SECOP II interventoria estudios disenos obras",
    ],
    seedUrls: [
      "https://www.colombiacompra.gov.co/secop/secop-ii",
      "https://community.secop.gov.co/Public/Tendering/ContractNoticeManagement/Index",
      "https://www.datos.gov.co/Gastos-Gubernamentales/SECOP-II-Procesos-de-Contrataci-n/p6dx-8zbt",
    ],
  },
  {
    id: "apc-colombia",
    name: "APC Colombia",
    tier: "nacional",
    domains: ["apccolombia.gov.co"],
    seedUrls: ["https://www.apccolombia.gov.co/convocatorias"],
  },
  {
    id: "minciencias",
    name: "Minciencias",
    tier: "nacional",
    connector: "mincienciasActeiPlan",
    domains: ["minciencias.gov.co"],
    seedUrls: ["https://minciencias.gov.co/plan-convocatorias-actei-2025-2026-0"],
  },
  {
    id: "mintic",
    name: "MinTIC",
    tier: "nacional",
    domains: ["mintic.gov.co"],
    seedUrls: ["https://www.mintic.gov.co/portal/inicio/convocatorias/"],
  },
  {
    id: "minambiente",
    name: "MinAmbiente",
    tier: "nacional",
    domains: ["minambiente.gov.co"],
    seedUrls: ["https://www.minambiente.gov.co/"],
  },
  {
    id: "dps",
    name: "DPS",
    tier: "nacional",
    domains: ["prosperidadsocial.gov.co"],
    seedUrls: ["https://prosperidadsocial.gov.co/"],
  },
  {
    id: "sgr",
    name: "SGR",
    tier: "nacional",
    domains: ["sgr.gov.co", "dnp.gov.co"],
    seedUrls: ["https://www.sgr.gov.co/"],
  },
  {
    id: "gobernaciones",
    name: "Gobernaciones",
    tier: "nacional",
    domains: ["gov.co"],
    seedUrls: ["https://www.gov.co/"],
  },
  {
    id: "findeter",
    name: "Findeter",
    tier: "nacional",
    domains: ["findeter.gov.co"],
    seedUrls: ["https://www.findeter.gov.co/"],
  },
  {
    id: "pnud",
    name: "PNUD",
    tier: "internacional",
    domains: ["undp.org"],
    seedUrls: ["https://www.undp.org/procurement/business-opportunities"],
  },
  {
    id: "ted-europa",
    name: "TED Europa",
    tier: "internacional",
    connector: "tedEuSearch",
    connectorQueries: [
      "publication-date>=today(-30) AND notice-type=cn-standard",
      "publication-date>=today(-30) AND notice-type=cn-standard AND notice-title~\"social\"",
      "publication-date>=today(-30) AND notice-type=cn-standard AND notice-title~\"education\"",
      "publication-date>=today(-30) AND notice-type=cn-standard AND notice-title~\"environment\"",
    ],
    domains: ["ted.europa.eu", "europa.eu"],
    seedUrls: ["https://ted.europa.eu/"],
  },
  {
    id: "europeaid",
    name: "Union Europea (EuropeAid)",
    tier: "internacional",
    domains: ["europa.eu", "ec.europa.eu"],
    seedUrls: ["https://international-partnerships.ec.europa.eu/funding_en"],
  },
  {
    id: "bid-lab",
    name: "BID Lab",
    tier: "internacional",
    domains: ["bidlab.org", "iadb.org"],
    seedUrls: ["https://bidlab.org/en/calls"],
  },
  {
    id: "caf",
    name: "CAF",
    tier: "internacional",
    domains: ["caf.com"],
    seedUrls: ["https://www.caf.com/en/"],
  },
  {
    id: "world-bank",
    name: "Banco Mundial",
    tier: "internacional",
    domains: ["worldbank.org"],
    seedUrls: ["https://www.worldbank.org/en/projects-operations/procurement"],
  },
  {
    id: "gef-small-grants",
    name: "GEF Small Grants",
    tier: "internacional",
    domains: ["sgp.undp.org", "thegef.org"],
    seedUrls: ["https://sgp.undp.org/"],
  },
  {
    id: "usaid",
    name: "USAID",
    tier: "internacional",
    connector: "grantsGovSearch2",
    connectorKeywords: [
      "community development",
      "education",
      "climate",
      "social inclusion",
      "institutional strengthening",
      "rural development",
      "innovation",
      "territorial",
    ],
    domains: ["usaid.gov", "grants.gov"],
    seedUrls: ["https://www.usaid.gov/work-usaid/partner-with-us"],
  },
  {
    id: "giz",
    name: "GIZ",
    tier: "internacional",
    domains: ["giz.de"],
    seedUrls: ["https://www.giz.de/en/worldwide/109163.html"],
  },
  {
    id: "embajadas",
    name: "Embajadas",
    tier: "internacional",
    domains: ["embassy", "gov"],
    seedUrls: ["https://www.cancilleria.gov.co/"],
  },
  {
    id: "google-org",
    name: "Google.org",
    tier: "internacional",
    domains: ["google.org"],
    searchKeywords: [
      "Google.org open call",
      "Google.org grant funding",
      "Google.org impact challenge",
      "Google.org request for proposals",
      "Google.org AI opportunity fund",
    ],
    seedUrls: [
      "https://www.google.org/",
      "https://www.google.org/open-calls/",
      "https://www.google.org/impactchallenge/",
      "https://www.google.org/our-work/",
    ],
  },
  {
    id: "un-org",
    name: "Naciones Unidas",
    tier: "internacional",
    domains: ["un.org", "ungm.org"],
    searchKeywords: [
      "Naciones Unidas convocatoria",
      "United Nations call for proposals",
      "United Nations procurement notice",
      "UNGM tender Colombia",
      "UNGM request for proposal",
      "UN partnership opportunity",
      "UN sustainable development grant",
    ],
    seedUrls: [
      "https://www.un.org/es/",
      "https://www.un.org/sustainabledevelopment/es/partnerships/",
      "https://www.ungm.org/Public/Notice",
      "https://www.ungm.org/Public/ContractAward",
    ],
  },
  {
    id: "wfp",
    name: "World Food Programme",
    tier: "internacional",
    domains: ["wfp.org"],
    searchKeywords: [
      "WFP procurement notice",
      "WFP tender",
      "WFP request for proposal",
      "WFP call for proposals",
      "World Food Programme partnership",
      "World Food Programme innovation accelerator call",
    ],
    seedUrls: [
      "https://www.wfp.org/",
      "https://www.wfp.org/procurement",
      "https://www.wfp.org/partners",
      "https://innovation.wfp.org/apply",
    ],
  },
  {
    id: "climate-funds",
    name: "Climate Funds",
    tier: "internacional",
    domains: ["climateinvestmentfunds.org", "greenclimate.fund"],
    seedUrls: ["https://www.climateinvestmentfunds.org/"],
  },
];

const DISCOVERY_KEYWORDS = [
  "convocatoria",
  "convocatoria abierta",
  "subvencion",
  "subvención",
  "cooperacion",
  "cooperación",
  "cooperacion internacional",
  "cooperación internacional",
  "financiacion",
  "financiación",
  "licitacion",
  "licitación",
  "contratacion",
  "contratación",
  "terminos de referencia",
  "términos de referencia",
  "secop",
  "secop ii",
  "concurso",
  "grant",
  "funding",
  "proposal",
  "call for proposals",
  "open call",
  "request for proposals",
  "rfp",
  "expression of interest",
  "eoi",
  "tender",
  "procurement",
  "notice",
  "partnership",
  "innovation challenge",
  "project",
  "territorial",
  "social",
  "ngo",
  "non-profit",
  "fundacion",
];

const OPPORTUNITY_URL_HINTS = [
  "convoc",
  "grant",
  "call",
  "proposal",
  "funding",
  "licit",
  "tender",
  "rfp",
  "eoi",
  "notice",
  "ungm",
  "vendor",
  "partner",
  "challenge",
  "procura",
  "contrat",
  "adquis",
  "opportun",
  "subvencion",
  "subvenci",
  "cooper",
  "procurement",
];

module.exports = {
  SOURCE_CATALOG,
  DISCOVERY_KEYWORDS,
  OPPORTUNITY_URL_HINTS,
};
